export const PASSWORD_HASH_SALT = 10;
export const JWT_ACCESS_TOKEN_EXPIRATION_TIME = '1d';
export const JWT_REFRESH_TOKEN_EXPIRATION_TIME = '2d';
export const JWT_FORGOT_PASSWORD_TOKEN_EXPIRATION_TIME = '5m';
